repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.7
    hooks:
      - id: ruff
        args: [ --fix, --extend-select, I ]
      - id: ruff-format
  - repo: local
    hooks:
      - id: system
        name: mypy
        entry: poetry run mypy .
        language: system
        files: \.(py)$
        pass_filenames: false
        require_serial: true
