# Generated by Django 5.0.4 on 2024-04-12 09:03

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=core.models.default_start_time, verbose_name='Время начала')),
                ('end_time', models.DateTimeField(default=core.models.default_end_time, verbose_name='Время окончания')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('location', models.CharField(max_length=256, verbose_name='Локация')),
                ('tickets_url', models.URLField(verbose_name='Ссылка на билеты')),
                ('image_url', models.ImageField(upload_to='events/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Мероприятиe',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
