# Generated by Django 5.0.4 on 2024-04-21 06:17

import uuid

from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def forwards(app: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Event = app.get_model('core', 'Event')
    for event in Event.objects.all():
        event.uuid = uuid.uuid4()
        event.save(update_fields=['uuid'])


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4,
                verbose_name='Идентификатор для каледнаря',
                null=True,
            ),
        ),
        migrations.RunPython(forwards),
        migrations.AddField(
            model_name='event',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4,
                verbose_name='Идентификатор для каледнаря',
            ),
        ),
    ]
