# Generated by Django 5.0.4 on 2024-04-24 04:19
from django.core.management import call_command
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def forwards(app: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    call_command('loaddata', 'core/fixtures/artists.json')


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_artist_rename_image_url_event_image'),
    ]

    operations = [
        # migrations.RunPython(forwards),
    ]
