# Generated by Django 5.0.4 on 2024-04-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_load_artists'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
