# Generated by Django 5.0.4 on 2024-04-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0005_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
    ]
