# Generated by Django 5.0.4 on 2024-09-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0006_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Показывать на странице'),
        ),
        migrations.AddField(
            model_name='event',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Показывать на странице'),
        ),
    ]
